### PR TITLE
possible fix of approval header

### PR DESCRIPTION
**Pull request by sylvihuynh**
Ref comment in #118. This is branched out from #118 
I added another title to distinguish the `assessment page`and `approval page` more. 
image

### CODE REVIEW

**Comment by amalieeh** [comment]
I think this needs rebase 😕 I was hoping that all the changes we did up until now was minor and would not cause conflicts, but it seams that they did... 
Would you like the honour? 😅

**Comment by sylvihuynh** [comment]
> I think this needs rebase 😕 I was hoping that all the changes we did up until now was minor and would not cause conflicts, but it seams that they did... Would you like the honour? 😅

Of course, cant miss such an honour!

**Comment by sylvihuynh** [comment]
Not sure if you saw my comment on #118 because there was a lot going on there. But the reason why I put a back arrow there that routes to the `assessment page` was to replace the originally `Tilbake` button at the bottom of the page.

We had a short discussion on that it may not be necessary to have the arrow  as this is an unlikely case. We could for instance replace it with a home button that routes to the task page. Not sure if it is obvious that home is task page though

**Review by amalieeh — APPROVED** [review]

**Comment by amalieeh** [comment]
Yeah that true, nice!

**Pull request merged**
