### PR TITLE
32 format answers

### LINKED ISSUE #32: Format answers nice
As of now there is just a half way working regex function `cleanHtmlText()` that replaces som characters ect. 
We should enable the formatting existing in the text (with html tags ++) and use it.

### LINKED ISSUE #77: Remove picture-url from answer length
Now, short answers are bumped to an unrepresentative spot in the order of assessments to display.
E.g. a medium length answer is displayed first, with very long answers, because of en extremely long image URL. 
Suggestion is to check for words longer than e.g. 30 chars or if it begins with 'src="data:image/'. And if found then assume it is an url and remove it from the count.

### PR DESCRIPTION
**Pull request by sylvihuynh**
fix #32
fix #77 

Added a converter that parses the html that wrap the student answers and returns beautiful text.
There is an edge case that if the student answers consist of html, it will be parsed and not displayed as a string in the text. 

image

### CODE REVIEW

**Review by amalieeh — COMMENTED** [review]
Good work! Nice that you found a way to reduce the font size a bit. And nice that you remembered to include the approval text boxes! There, the images gets too big, but since they are gonna be redesigned, I think that is fine.

The only thing is the issue you addressed: If someone writes a html tag in the text, it fucks up the text.
Did you try the "dangerously input" variant? Or we could make an bug on it instantly? I feel like this PR is good _enough_ for test purposes, so just creating a bug on it is fine!

**Comment by sylvihuynh** [comment]
> 
No, but I can try it now

**Comment by sylvihuynh** [comment]
> > 
> 
> No, but I can try it now

Ok, I tried and it looks the same. So we can create a bug issue

**Review by amalieeh — APPROVED** [review]
Good work! Thank you for testing the other approach! 🙌

**Pull request merged**
