### PR TITLE
New suggestion for displaying task titles

### PR DESCRIPTION
**Pull request by sylvihuynh**
Created a list of the task titles with your suggestions from #55

### CODE REVIEW

**Comment by amalieeh** [comment]
Wow, good job! :) Thank you for being so considerate of my oipinion! I think however my explanation on the last PR was bad 😅
Regarding design, in your ideal, what would be nice to have on task page?

**Comment by sylvihuynh** [comment]
> Wow, good job! :) Thank you for being so considerate of my opinion! I think however my explanation on the last PR was bad 😅 Regarding design, in your ideal, what would be nice to have on task page?

If we want to have it with a menu, I think I would like to have it like the exams on  Inspera's last page that sums it all up. This is similar to my first suggestion with clickable buttons, but they would rather cover more of the page like Inspera. With this suggestion, we will no longer have the current buttons with the color codes. I like the color coding but with the full menu I think it will be disturbing to have different colors on each line.

**Comment by amalieeh** [comment]
> >Wow, good job! :) Thank you for being so considerate of my opinion! I think however my explanation on the last PR was bad 😅 Regarding design, in your ideal, what would be nice to have on task page?

> If we want to have it with a menu, I think I would like to have it like the exams on Inspera's last page that sums it all up. This is similar to my first suggestion with clickable buttons, but they would rather cover more of the page like Inspera. With this suggestion, we will no longer have the current buttons with the color codes. I like the color coding but with the full menu I think it will be disturbing to have different colors on each line.

I totally agree! I think:) So removing the buttons and having the clickable list like in #121 ?
Potentially upgrade by having a checkbox on the side or something 😅

**Comment by sylvihuynh** [comment]
> > > Wow, good job! :) Thank you for being so considerate of my opinion! I think however my explanation on the last PR was bad 😅 Regarding design, in your ideal, what would be nice to have on task page?
> 
> > If we want to have it with a menu, I think I would like to have it like the exams on Inspera's last page that sums it all up. This is similar to my first suggestion with clickable buttons, but they would rather cover more of the page like Inspera. With this suggestion, we will no longer have the current buttons with the color codes. I like the color coding but with the full menu I think it will be disturbing to have different colors on each line.
> 
> I totally agree! I think:) So removing the buttons and having the clickable list like in #121 ? Potentially upgrade by having a checkbox on the side or something 😅

Yees, but I do not have time to fix this tomorrow, so unfortunately we will not be able to have it by the _kodefrys_... 😞 So we can just keep it as it is now for the testing purposes.

**Pull request closed without merging**
