### PR TITLE
81 sort answers

### LINKED ISSUE #81: Present (and implement) options for sorting answers
The user should have the possibility to choose which option they would like to have the answers displayed. The options could be presented in a menu on the left side of the screen. Options that should be: 
- random
- candidate number
- answers that are alike
- answers that are unlike

### PR DESCRIPTION
**Pull request by sylvihuynh**
fix #81 

Created a drop down sorting box where the user can choose to sort the student answers byb:
- random
- candidate number
- length - high to low
- length - low to high

This currently works for the case when the data is loaded and no assessments have been made.
It later needs to be updated to only sort the rest of the assessments that have not been assessed.
This is in relation to data retrieval for textboxes.

### CODE REVIEW

**Comment by amalieeh** [comment]
Nice work!!

I feel like the box is a bit "unaligned" with the oppgavebeskrivelse-section, but I think it is nice that it is clear that it is in no connection to oppgavebeskrivelse. Also i think this is something #88 or another css-issue can look at. 
(Personally, I think that the oppgavebeskrivelse-section should be moved down to align with the textboxes)
image

So I think that no change is needed, just shared a thought.

**Comment by sylvihuynh** [comment]
> Nice work!!
> 
> I feel like the box is a bit "unaligned" with the oppgavebeskrivelse-section, but I think it is nice that it is clear that it is in no connection to oppgavebeskrivelse. Also i think this is something #88 or another css-issue can look at. (Personally, I think that the oppgavebeskrivelse-section should be moved down to align with the textboxes) image
> 
> So I think that no change is needed, just shared a thought.
> 
> _Edit: Actually I see that the oppgavebeskrivelser-section used to be aligned with the texboxes. Is it hard to fix? I get if the change happens in #105 instead of here so you dont get rebase issues_

I agree, and will take a look at it 👍

**Review by amalieeh — APPROVED** [review]
Great! 🔥

**Comment by sylvihuynh** [comment]
I added margin to the oppgavebeskrivelse-section, but as I do not know the size of the sorting box I added margin by eye, so please have a look too 👁️

**Comment by amalieeh** [comment]
Makes aaall the difference! :))

But now it seems like the alignment of the oppgavebeskrivelse-section and textboxes is gone? Like you fixed earlier with margin-top:59 or something like that. Does it look like this on your computer as well?
Was it on purpose?
image

**Pull request merged**
